"""baseline: initial schema (10 tables)

Revision ID: 0f9b955554fe
Revises: 
Create Date: 2026-07-09 04:06:24.535015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f9b955554fe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corporate_actions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('announcement_date', sa.String(), nullable=True),
    sa.Column('ex_date', sa.String(), nullable=False),
    sa.Column('record_date', sa.String(), nullable=True),
    sa.Column('payment_date', sa.String(), nullable=True),
    sa.Column('action_data', sa.String(), nullable=False),
    sa.Column('is_confirmed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_applied', sa.Integer(), server_default='0', nullable=False),
    sa.Column('source', sa.String(), server_default='manual', nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('raw_data', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.CheckConstraint("action_type IN ('DIVIDEND', 'BONUS_SHARE', 'RIGHTS_ISSUE', 'SPLIT', 'REVERSE_SPLIT', 'MERGER', 'SPIN_OFF', 'DELISTING')", name='chk_action_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funds',
    sa.Column('fund_code', sa.String(), nullable=False),
    sa.Column('fund_name', sa.String(), nullable=False),
    sa.Column('fund_type', sa.String(), nullable=False),
    sa.Column('umbrella_type', sa.String(), nullable=True),
    sa.Column('founder', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), server_default='TRY', nullable=False),
    sa.Column('stock_pct', sa.String(), nullable=True),
    sa.Column('bond_pct', sa.String(), nullable=True),
    sa.Column('repo_pct', sa.String(), nullable=True),
    sa.Column('foreign_stock_pct', sa.String(), nullable=True),
    sa.Column('gold_pct', sa.String(), nullable=True),
    sa.Column('other_pct', sa.String(), nullable=True),
    sa.Column('allocation_date', sa.String(), nullable=True),
    sa.Column('last_nav', sa.String(), nullable=True),
    sa.Column('last_nav_date', sa.String(), nullable=True),
    sa.Column('ytd_return', sa.String(), nullable=True),
    sa.Column('management_fee', sa.String(), nullable=True),
    sa.Column('is_active', sa.Integer(), server_default='1', nullable=False),
    sa.Column('last_updated', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.CheckConstraint("fund_type IN ('YAT', 'EMK', 'BYF', 'DIGER')", name='chk_fund_type'),
    sa.PrimaryKeyConstraint('fund_code')
    )
    op.create_table('portfolios',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), server_default='TRY', nullable=False),
    sa.Column('cost_method', sa.String(), server_default='WAVG', nullable=False),
    sa.Column('inception_date', sa.String(), nullable=False),
    sa.Column('benchmark_code', sa.String(), nullable=True),
    sa.Column('is_active', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('metadata', sa.String(), nullable=True),
    sa.CheckConstraint("cost_method IN ('WAVG', 'FIFO', 'LIFO')", name='chk_cost_method'),
    sa.CheckConstraint("currency IN ('TRY', 'USD', 'EUR')", name='chk_portfolio_currency'),
    sa.CheckConstraint('is_active IN (0, 1)', name='chk_portfolio_is_active'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_portfolio_name')
    )
    op.create_table('price_series',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('symbol_type', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('open_price', sa.String(), nullable=True),
    sa.Column('high_price', sa.String(), nullable=True),
    sa.Column('low_price', sa.String(), nullable=True),
    sa.Column('close_price', sa.String(), nullable=False),
    sa.Column('adjusted_close', sa.String(), nullable=True),
    sa.Column('volume', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('is_holiday', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.CheckConstraint("source IN ('yfinance', 'tefas', 'isyatirim', 'bist', 'manual', 'mock')", name='chk_price_source'),
    sa.CheckConstraint("symbol_type IN ('BIST_STOCK', 'TEFAS_FUND', 'BIST_ETF', 'BENCHMARK')", name='chk_price_symbol_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', name='uq_price_symbol_date')
    )
    op.create_table('risk_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('portfolio_id', sa.String(), nullable=False),
    sa.Column('computed_at', sa.String(), nullable=False),
    sa.Column('as_of_date', sa.String(), nullable=False),
    sa.Column('lookback_days', sa.Integer(), nullable=False),
    sa.Column('portfolio_volatility', sa.Float(), nullable=True),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('sortino_ratio', sa.Float(), nullable=True),
    sa.Column('calmar_ratio', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('max_drawdown_start', sa.String(), nullable=True),
    sa.Column('max_drawdown_end', sa.String(), nullable=True),
    sa.Column('current_drawdown', sa.Float(), nullable=True),
    sa.Column('var_95', sa.Float(), nullable=True),
    sa.Column('var_99', sa.Float(), nullable=True),
    sa.Column('cvar_95', sa.Float(), nullable=True),
    sa.Column('cvar_99', sa.Float(), nullable=True),
    sa.Column('var_method', sa.String(), server_default='HISTORICAL', nullable=False),
    sa.Column('beta', sa.Float(), nullable=True),
    sa.Column('alpha', sa.Float(), nullable=True),
    sa.Column('r_squared', sa.Float(), nullable=True),
    sa.Column('information_ratio', sa.Float(), nullable=True),
    sa.Column('tracking_error', sa.Float(), nullable=True),
    sa.Column('herfindahl_index', sa.Float(), nullable=True),
    sa.Column('top5_concentration', sa.Float(), nullable=True),
    sa.Column('risk_free_rate', sa.Float(), nullable=False),
    sa.Column('benchmark_code', sa.String(), nullable=True),
    sa.Column('is_stale', sa.Integer(), server_default='0', nullable=False),
    sa.CheckConstraint("var_method IN ('HISTORICAL', 'PARAMETRIC', 'MONTECARLO')", name='chk_snapshot_var_method'),
    sa.CheckConstraint('is_stale IN (0, 1)', name='chk_snapshot_is_stale'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('portfolio_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('symbol_type', sa.String(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('quantity', sa.String(), nullable=False),
    sa.Column('price', sa.String(), nullable=False),
    sa.Column('net_amount', sa.String(), nullable=True),
    sa.Column('split_ratio', sa.String(), nullable=True),
    sa.Column('trade_date', sa.String(), nullable=False),
    sa.Column('is_active', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('is_reversal', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reversal_of', sa.String(), nullable=True),
    sa.Column('reversal_reason', sa.String(), nullable=True),
    sa.CheckConstraint("symbol_type IN ('BIST_STOCK', 'TEFAS_FUND', 'BIST_ETF', 'BOND', 'CASH', 'OTHER')", name='chk_symbol_type'),
    sa.CheckConstraint("transaction_type IN ('BUY','SELL','DIVIDEND','BONUS_SHARE','RIGHTS_USED','RIGHTS_SOLD','SPLIT','REVERSE_SPLIT','MERGER','DEPOSIT','WITHDRAWAL','FEE','TAX')", name='chk_transaction_type'),
    sa.CheckConstraint('is_active IN (0, 1)', name='chk_tx_is_active'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.ForeignKeyConstraint(['reversal_of'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watchlists',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('portfolio_id', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cash_ledger_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('portfolio_id', sa.String(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=True),
    sa.Column('entry_type', sa.String(), nullable=False),
    sa.Column('amount', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), server_default='TRY', nullable=False),
    sa.Column('entry_date', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('balance_after', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.CheckConstraint("entry_type IN ('CREDIT', 'DEBIT')", name='chk_entry_type'),
    sa.CheckConstraint('CAST(amount AS REAL) > 0', name='chk_amount_positive'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watchlist_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('watchlist_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('symbol_type', sa.String(), nullable=False),
    sa.Column('alert_price_low', sa.String(), nullable=True),
    sa.Column('alert_price_high', sa.String(), nullable=True),
    sa.Column('alert_pct_change', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('added_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('watchlist_id', 'symbol', name='uq_watchlist_symbol')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist_items')
    op.drop_table('cash_ledger_entries')
    op.drop_table('watchlists')
    op.drop_table('transactions')
    op.drop_table('risk_snapshots')
    op.drop_table('price_series')
    op.drop_table('portfolios')
    op.drop_table('funds')
    op.drop_table('corporate_actions')
    # ### end Alembic commands ###
